version: "3.3"
services:
  poc:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    container_name: poc-pulsar
    networks:
      - infra_partyou-local
    volumes:
      - .:/src:Z

networks:
  infra_partyou-local:
    external: true
